<a href="https://colab.research.google.com/github/Indramawanciputra28/Data-Mining/blob/main/Preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks.
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot. ...

In [37]:
dataset = pd.read_csv('Datakaryawan.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [38]:
print(x)

[['Andi' 30.0 7000000.0 'Manager']
 ['Budi' nan 4500000.0 'Staff']
 ['Citra' 28.0 nan 'Supervisor']
 ['Dedi' 35.0 8500000.0 'Manager']
 ['Evi' 22.0 4000000.0 nan]
 ['Fajar' nan 9500000.0 'Direktur']
 ['Gina' 33.0 7000000.0 'Supervisor']
 ['Hana' 29.0 nan 'Staff']
 ['Ilham' 38.0 8500000.0 'Manager']
 ['Joko' 45.0 10000000.0 nan]
 ['Kiki' 27.0 4800000.0 'Staff']
 ['Lia' nan 5200000.0 'Supervisor']
 ['Maman' 32.0 6200000.0 'Supervisor']
 ['Nia' 24.0 4700000.0 nan]
 ['Oki' 41.0 nan 'Direktur']]


In [39]:
print(y)

['Ya' 'Tidak' 'Ya' 'Ya' 'Tidak' 'Ya' nan 'Tidak' 'Ya' 'Ya' 'Ya' 'Ya'
 'Tidak' 'Ya' 'Tidak']


In [40]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [41]:
print(x)

[['Andi' 30.0 7000000.0 'Manager']
 ['Budi' 32.0 4500000.0 'Staff']
 ['Citra' 28.0 6658333.333333333 'Supervisor']
 ['Dedi' 35.0 8500000.0 'Manager']
 ['Evi' 22.0 4000000.0 nan]
 ['Fajar' 32.0 9500000.0 'Direktur']
 ['Gina' 33.0 7000000.0 'Supervisor']
 ['Hana' 29.0 6658333.333333333 'Staff']
 ['Ilham' 38.0 8500000.0 'Manager']
 ['Joko' 45.0 10000000.0 nan]
 ['Kiki' 27.0 4800000.0 'Staff']
 ['Lia' 32.0 5200000.0 'Supervisor']
 ['Maman' 32.0 6200000.0 'Supervisor']
 ['Nia' 24.0 4700000.0 nan]
 ['Oki' 41.0 6658333.333333333 'Direktur']]


In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler # Importing StandardScaler
import numpy as np # Importing numpy for array operations
from sklearn.pipeline import Pipeline # Importing the Pipeline class

# Assuming 'x' is your original data
# Define columns for each data type
categorical_features = [0]  # Column index for categorical features (e.g., Country)
numerical_features = [1, 2] # Column indices for numerical features (e.g., Age, Salary)

# Create transformers for each data

In [43]:
print(x)

[['Andi' 30.0 7000000.0 'Manager']
 ['Budi' 32.0 4500000.0 'Staff']
 ['Citra' 28.0 6658333.333333333 'Supervisor']
 ['Dedi' 35.0 8500000.0 'Manager']
 ['Evi' 22.0 4000000.0 nan]
 ['Fajar' 32.0 9500000.0 'Direktur']
 ['Gina' 33.0 7000000.0 'Supervisor']
 ['Hana' 29.0 6658333.333333333 'Staff']
 ['Ilham' 38.0 8500000.0 'Manager']
 ['Joko' 45.0 10000000.0 nan]
 ['Kiki' 27.0 4800000.0 'Staff']
 ['Lia' 32.0 5200000.0 'Supervisor']
 ['Maman' 32.0 6200000.0 'Supervisor']
 ['Nia' 24.0 4700000.0 nan]
 ['Oki' 41.0 6658333.333333333 'Direktur']]


In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [45]:
print(y)

[1 0 1 1 0 1 2 0 1 1 1 1 0 1 0]


In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [47]:
print(x_train)

[['Citra' 28.0 6658333.333333333 'Supervisor']
 ['Kiki' 27.0 4800000.0 'Staff']
 ['Evi' 22.0 4000000.0 nan]
 ['Budi' 32.0 4500000.0 'Staff']
 ['Nia' 24.0 4700000.0 nan]
 ['Andi' 30.0 7000000.0 'Manager']
 ['Oki' 41.0 6658333.333333333 'Direktur']
 ['Joko' 45.0 10000000.0 nan]
 ['Ilham' 38.0 8500000.0 'Manager']
 ['Maman' 32.0 6200000.0 'Supervisor']
 ['Lia' 32.0 5200000.0 'Supervisor']
 ['Fajar' 32.0 9500000.0 'Direktur']]


In [48]:
print(x_test)

[['Dedi' 35.0 8500000.0 'Manager']
 ['Hana' 29.0 6658333.333333333 'Staff']
 ['Gina' 33.0 7000000.0 'Supervisor']]


In [49]:
print(y_train)

[1 1 0 0 1 1 0 1 1 0 1 1]


In [50]:
print(y_test)

[1 0 2]


In [51]:
!pip install pandas scikit-learn
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Assuming x_train is a NumPy array, convert it to a pandas DataFrame for easier manipulation
x_train_df = pd.DataFrame(x_train)

# Assuming the column at index 3 contains the string values (like 'Supervisor')
categorical_features = [3]  # Replace 3 with the actual index of the categorical column

# Create a ColumnTransformer to apply OneHotEncoder to the categorical column and StandardScaler to the rest
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), [i for i in range(x_train_df.shape[1])])
    ])

In [52]:
print(x_train)

[['Citra' 28.0 6658333.333333333 'Supervisor']
 ['Kiki' 27.0 4800000.0 'Staff']
 ['Evi' 22.0 4000000.0 nan]
 ['Budi' 32.0 4500000.0 'Staff']
 ['Nia' 24.0 4700000.0 nan]
 ['Andi' 30.0 7000000.0 'Manager']
 ['Oki' 41.0 6658333.333333333 'Direktur']
 ['Joko' 45.0 10000000.0 nan]
 ['Ilham' 38.0 8500000.0 'Manager']
 ['Maman' 32.0 6200000.0 'Supervisor']
 ['Lia' 32.0 5200000.0 'Supervisor']
 ['Fajar' 32.0 9500000.0 'Direktur']]


In [53]:
print(x_test)

[['Dedi' 35.0 8500000.0 'Manager']
 ['Hana' 29.0 6658333.333333333 'Staff']
 ['Gina' 33.0 7000000.0 'Supervisor']]
